; http://jonls.dk/redshift/

[redshift]
; Set the day and night screen temperatures 6500 = no change
temp-day=6500
temp-night=3500

brightness-day=1
brightness-night=0.3 ; bedroom at night darkness, but doesn't go bright enough elsewhere
; brightness-night=0.8 ; sitting room at night, less backlight needed

[manual]
lat=51.3598
lon=-1.1485
